name: The Chief
favicon: null
layout_spectrum: 0.4522875314578414
typography_spectrum: 0.8757542732637376
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0c1b'
    - '#f8e8db'
    - '#0a3d2a'
    - '#cdc6bc'
    - '#3b7155'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
